<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

namespace Lnrpc\NewAddressRequest;

/**
 * Protobuf type <code>lnrpc.NewAddressRequest.AddressType</code>
 */
class AddressType
{
    /**
     * Generated from protobuf enum <code>WITNESS_PUBKEY_HASH = 0;</code>
     */
    const WITNESS_PUBKEY_HASH = 0;
    /**
     * Generated from protobuf enum <code>NESTED_PUBKEY_HASH = 1;</code>
     */
    const NESTED_PUBKEY_HASH = 1;
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(AddressType::class, \Lnrpc\NewAddressRequest_AddressType::class);

