<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

namespace Lnrpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>lnrpc.ActiveChannel</code>
 */
class ActiveChannel extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>bool active = 1[json_name = "active"];</code>
     */
    private $active = false;
    /**
     * <code>string remote_pubkey = 2[json_name = "remote_pubkey"];</code>
     */
    private $remote_pubkey = '';
    /**
     * <code>string channel_point = 3[json_name = "channel_point"];</code>
     */
    private $channel_point = '';
    /**
     * <code>uint64 chan_id = 4[json_name = "chan_id"];</code>
     */
    private $chan_id = 0;
    /**
     * <code>int64 capacity = 5[json_name = "capacity"];</code>
     */
    private $capacity = 0;
    /**
     * <code>int64 local_balance = 6[json_name = "local_balance"];</code>
     */
    private $local_balance = 0;
    /**
     * <code>int64 remote_balance = 7[json_name = "remote_balance"];</code>
     */
    private $remote_balance = 0;
    /**
     * <code>int64 unsettled_balance = 8[json_name = "unsettled_balance"];</code>
     */
    private $unsettled_balance = 0;
    /**
     * <code>int64 total_satoshis_sent = 9[json_name = "total_satoshis_sent"];</code>
     */
    private $total_satoshis_sent = 0;
    /**
     * <code>int64 total_satoshis_received = 10[json_name = "total_satoshis_received"];</code>
     */
    private $total_satoshis_received = 0;
    /**
     * <code>uint64 num_updates = 11[json_name = "num_updates"];</code>
     */
    private $num_updates = 0;
    /**
     * <code>repeated .lnrpc.HTLC pending_htlcs = 12[json_name = "pending_htlcs"];</code>
     */
    private $pending_htlcs;

    public function __construct() {
        \GPBMetadata\Rpc::initOnce();
        parent::__construct();
    }

    /**
     * <code>bool active = 1[json_name = "active"];</code>
     */
    public function getActive()
    {
        return $this->active;
    }

    /**
     * <code>bool active = 1[json_name = "active"];</code>
     */
    public function setActive($var)
    {
        GPBUtil::checkBool($var);
        $this->active = $var;
    }

    /**
     * <code>string remote_pubkey = 2[json_name = "remote_pubkey"];</code>
     */
    public function getRemotePubkey()
    {
        return $this->remote_pubkey;
    }

    /**
     * <code>string remote_pubkey = 2[json_name = "remote_pubkey"];</code>
     */
    public function setRemotePubkey($var)
    {
        GPBUtil::checkString($var, True);
        $this->remote_pubkey = $var;
    }

    /**
     * <code>string channel_point = 3[json_name = "channel_point"];</code>
     */
    public function getChannelPoint()
    {
        return $this->channel_point;
    }

    /**
     * <code>string channel_point = 3[json_name = "channel_point"];</code>
     */
    public function setChannelPoint($var)
    {
        GPBUtil::checkString($var, True);
        $this->channel_point = $var;
    }

    /**
     * <code>uint64 chan_id = 4[json_name = "chan_id"];</code>
     */
    public function getChanId()
    {
        return $this->chan_id;
    }

    /**
     * <code>uint64 chan_id = 4[json_name = "chan_id"];</code>
     */
    public function setChanId($var)
    {
        GPBUtil::checkUint64($var);
        $this->chan_id = $var;
    }

    /**
     * <code>int64 capacity = 5[json_name = "capacity"];</code>
     */
    public function getCapacity()
    {
        return $this->capacity;
    }

    /**
     * <code>int64 capacity = 5[json_name = "capacity"];</code>
     */
    public function setCapacity($var)
    {
        GPBUtil::checkInt64($var);
        $this->capacity = $var;
    }

    /**
     * <code>int64 local_balance = 6[json_name = "local_balance"];</code>
     */
    public function getLocalBalance()
    {
        return $this->local_balance;
    }

    /**
     * <code>int64 local_balance = 6[json_name = "local_balance"];</code>
     */
    public function setLocalBalance($var)
    {
        GPBUtil::checkInt64($var);
        $this->local_balance = $var;
    }

    /**
     * <code>int64 remote_balance = 7[json_name = "remote_balance"];</code>
     */
    public function getRemoteBalance()
    {
        return $this->remote_balance;
    }

    /**
     * <code>int64 remote_balance = 7[json_name = "remote_balance"];</code>
     */
    public function setRemoteBalance($var)
    {
        GPBUtil::checkInt64($var);
        $this->remote_balance = $var;
    }

    /**
     * <code>int64 unsettled_balance = 8[json_name = "unsettled_balance"];</code>
     */
    public function getUnsettledBalance()
    {
        return $this->unsettled_balance;
    }

    /**
     * <code>int64 unsettled_balance = 8[json_name = "unsettled_balance"];</code>
     */
    public function setUnsettledBalance($var)
    {
        GPBUtil::checkInt64($var);
        $this->unsettled_balance = $var;
    }

    /**
     * <code>int64 total_satoshis_sent = 9[json_name = "total_satoshis_sent"];</code>
     */
    public function getTotalSatoshisSent()
    {
        return $this->total_satoshis_sent;
    }

    /**
     * <code>int64 total_satoshis_sent = 9[json_name = "total_satoshis_sent"];</code>
     */
    public function setTotalSatoshisSent($var)
    {
        GPBUtil::checkInt64($var);
        $this->total_satoshis_sent = $var;
    }

    /**
     * <code>int64 total_satoshis_received = 10[json_name = "total_satoshis_received"];</code>
     */
    public function getTotalSatoshisReceived()
    {
        return $this->total_satoshis_received;
    }

    /**
     * <code>int64 total_satoshis_received = 10[json_name = "total_satoshis_received"];</code>
     */
    public function setTotalSatoshisReceived($var)
    {
        GPBUtil::checkInt64($var);
        $this->total_satoshis_received = $var;
    }

    /**
     * <code>uint64 num_updates = 11[json_name = "num_updates"];</code>
     */
    public function getNumUpdates()
    {
        return $this->num_updates;
    }

    /**
     * <code>uint64 num_updates = 11[json_name = "num_updates"];</code>
     */
    public function setNumUpdates($var)
    {
        GPBUtil::checkUint64($var);
        $this->num_updates = $var;
    }

    /**
     * <code>repeated .lnrpc.HTLC pending_htlcs = 12[json_name = "pending_htlcs"];</code>
     */
    public function getPendingHtlcs()
    {
        return $this->pending_htlcs;
    }

    /**
     * <code>repeated .lnrpc.HTLC pending_htlcs = 12[json_name = "pending_htlcs"];</code>
     */
    public function setPendingHtlcs(&$var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Lnrpc\HTLC::class);
        $this->pending_htlcs = $arr;
    }

}

