<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

namespace Lnrpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>lnrpc.ChannelGraphRequest</code>
 */
class ChannelGraphRequest extends \Google\Protobuf\Internal\Message
{

    public function __construct() {
        \GPBMetadata\Rpc::initOnce();
        parent::__construct();
    }

}

