<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

namespace Lnrpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>lnrpc.ChannelEdgeUpdate</code>
 */
class ChannelEdgeUpdate extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>uint64 chan_id = 1;</code>
     */
    private $chan_id = 0;
    /**
     * <code>.lnrpc.ChannelPoint chan_point = 2;</code>
     */
    private $chan_point = null;
    /**
     * <code>int64 capacity = 3;</code>
     */
    private $capacity = 0;
    /**
     * <code>.lnrpc.RoutingPolicy routing_policy = 4;</code>
     */
    private $routing_policy = null;
    /**
     * <code>string advertising_node = 5;</code>
     */
    private $advertising_node = '';
    /**
     * <code>string connecting_node = 6;</code>
     */
    private $connecting_node = '';

    public function __construct() {
        \GPBMetadata\Rpc::initOnce();
        parent::__construct();
    }

    /**
     * <code>uint64 chan_id = 1;</code>
     */
    public function getChanId()
    {
        return $this->chan_id;
    }

    /**
     * <code>uint64 chan_id = 1;</code>
     */
    public function setChanId($var)
    {
        GPBUtil::checkUint64($var);
        $this->chan_id = $var;
    }

    /**
     * <code>.lnrpc.ChannelPoint chan_point = 2;</code>
     */
    public function getChanPoint()
    {
        return $this->chan_point;
    }

    /**
     * <code>.lnrpc.ChannelPoint chan_point = 2;</code>
     */
    public function setChanPoint(&$var)
    {
        GPBUtil::checkMessage($var, \Lnrpc\ChannelPoint::class);
        $this->chan_point = $var;
    }

    /**
     * <code>int64 capacity = 3;</code>
     */
    public function getCapacity()
    {
        return $this->capacity;
    }

    /**
     * <code>int64 capacity = 3;</code>
     */
    public function setCapacity($var)
    {
        GPBUtil::checkInt64($var);
        $this->capacity = $var;
    }

    /**
     * <code>.lnrpc.RoutingPolicy routing_policy = 4;</code>
     */
    public function getRoutingPolicy()
    {
        return $this->routing_policy;
    }

    /**
     * <code>.lnrpc.RoutingPolicy routing_policy = 4;</code>
     */
    public function setRoutingPolicy(&$var)
    {
        GPBUtil::checkMessage($var, \Lnrpc\RoutingPolicy::class);
        $this->routing_policy = $var;
    }

    /**
     * <code>string advertising_node = 5;</code>
     */
    public function getAdvertisingNode()
    {
        return $this->advertising_node;
    }

    /**
     * <code>string advertising_node = 5;</code>
     */
    public function setAdvertisingNode($var)
    {
        GPBUtil::checkString($var, True);
        $this->advertising_node = $var;
    }

    /**
     * <code>string connecting_node = 6;</code>
     */
    public function getConnectingNode()
    {
        return $this->connecting_node;
    }

    /**
     * <code>string connecting_node = 6;</code>
     */
    public function setConnectingNode($var)
    {
        GPBUtil::checkString($var, True);
        $this->connecting_node = $var;
    }

}

