<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

namespace Lnrpc;

if (false) {
    /**
     * This class is deprecated. Use Lnrpc\ChannelCloseSummary\ClosureType instead.
     * @deprecated
     */
    class ChannelCloseSummary_ClosureType {}
}
class_exists(ChannelCloseSummary\ClosureType::class);
@trigger_error('Lnrpc\ChannelCloseSummary_ClosureType is deprecated and will be removed in the next major release. Use Lnrpc\ChannelCloseSummary\ClosureType instead', E_USER_DEPRECATED);

