<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

namespace Lnrpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>lnrpc.ChannelPoint</code>
 */
class ChannelPoint extends \Google\Protobuf\Internal\Message
{
    /**
     *&#47; The index of the output of the funding transaction
     *
     * Generated from protobuf field <code>uint32 output_index = 3[json_name = "output_index"];</code>
     */
    private $output_index = 0;
    protected $funding_txid;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $funding_txid_bytes
     *          &#47; Txid of the funding transaction
     *     @type string $funding_txid_str
     *          &#47; Hex-encoded string representing the funding transaction
     *     @type int $output_index
     *          &#47; The index of the output of the funding transaction
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Rpc::initOnce();
        parent::__construct($data);
    }

    /**
     *&#47; Txid of the funding transaction
     *
     * Generated from protobuf field <code>bytes funding_txid_bytes = 1[json_name = "funding_txid_bytes"];</code>
     * @return string
     */
    public function getFundingTxidBytes()
    {
        return $this->readOneof(1);
    }

    /**
     *&#47; Txid of the funding transaction
     *
     * Generated from protobuf field <code>bytes funding_txid_bytes = 1[json_name = "funding_txid_bytes"];</code>
     * @param string $var
     * @return $this
     */
    public function setFundingTxidBytes($var)
    {
        GPBUtil::checkString($var, False);
        $this->writeOneof(1, $var);

        return $this;
    }

    /**
     *&#47; Hex-encoded string representing the funding transaction
     *
     * Generated from protobuf field <code>string funding_txid_str = 2[json_name = "funding_txid_str"];</code>
     * @return string
     */
    public function getFundingTxidStr()
    {
        return $this->readOneof(2);
    }

    /**
     *&#47; Hex-encoded string representing the funding transaction
     *
     * Generated from protobuf field <code>string funding_txid_str = 2[json_name = "funding_txid_str"];</code>
     * @param string $var
     * @return $this
     */
    public function setFundingTxidStr($var)
    {
        GPBUtil::checkString($var, True);
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     *&#47; The index of the output of the funding transaction
     *
     * Generated from protobuf field <code>uint32 output_index = 3[json_name = "output_index"];</code>
     * @return int
     */
    public function getOutputIndex()
    {
        return $this->output_index;
    }

    /**
     *&#47; The index of the output of the funding transaction
     *
     * Generated from protobuf field <code>uint32 output_index = 3[json_name = "output_index"];</code>
     * @param int $var
     * @return $this
     */
    public function setOutputIndex($var)
    {
        GPBUtil::checkUint32($var);
        $this->output_index = $var;

        return $this;
    }

    /**
     * @return string
     */
    public function getFundingTxid()
    {
        return $this->whichOneof("funding_txid");
    }

}

