<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

namespace Lnrpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>lnrpc.ChannelEdge</code>
 */
class ChannelEdge extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>uint64 channel_id = 1[json_name = "channel_id"];</code>
     */
    private $channel_id = 0;
    /**
     * <code>string chan_point = 2[json_name = "chan_point"];</code>
     */
    private $chan_point = '';
    /**
     * <code>uint32 last_update = 3[json_name = "last_update"];</code>
     */
    private $last_update = 0;
    /**
     * <code>string node1_pub = 4[json_name = "node1_pub"];</code>
     */
    private $node1_pub = '';
    /**
     * <code>string node2_pub = 5[json_name = "node2_pub"];</code>
     */
    private $node2_pub = '';
    /**
     * <code>int64 capacity = 6[json_name = "capacity"];</code>
     */
    private $capacity = 0;
    /**
     * <code>.lnrpc.RoutingPolicy node1_policy = 7[json_name = "node1_policy"];</code>
     */
    private $node1_policy = null;
    /**
     * <code>.lnrpc.RoutingPolicy node2_policy = 8[json_name = "node2_policy"];</code>
     */
    private $node2_policy = null;

    public function __construct() {
        \GPBMetadata\Rpc::initOnce();
        parent::__construct();
    }

    /**
     * <code>uint64 channel_id = 1[json_name = "channel_id"];</code>
     */
    public function getChannelId()
    {
        return $this->channel_id;
    }

    /**
     * <code>uint64 channel_id = 1[json_name = "channel_id"];</code>
     */
    public function setChannelId($var)
    {
        GPBUtil::checkUint64($var);
        $this->channel_id = $var;
    }

    /**
     * <code>string chan_point = 2[json_name = "chan_point"];</code>
     */
    public function getChanPoint()
    {
        return $this->chan_point;
    }

    /**
     * <code>string chan_point = 2[json_name = "chan_point"];</code>
     */
    public function setChanPoint($var)
    {
        GPBUtil::checkString($var, True);
        $this->chan_point = $var;
    }

    /**
     * <code>uint32 last_update = 3[json_name = "last_update"];</code>
     */
    public function getLastUpdate()
    {
        return $this->last_update;
    }

    /**
     * <code>uint32 last_update = 3[json_name = "last_update"];</code>
     */
    public function setLastUpdate($var)
    {
        GPBUtil::checkUint32($var);
        $this->last_update = $var;
    }

    /**
     * <code>string node1_pub = 4[json_name = "node1_pub"];</code>
     */
    public function getNode1Pub()
    {
        return $this->node1_pub;
    }

    /**
     * <code>string node1_pub = 4[json_name = "node1_pub"];</code>
     */
    public function setNode1Pub($var)
    {
        GPBUtil::checkString($var, True);
        $this->node1_pub = $var;
    }

    /**
     * <code>string node2_pub = 5[json_name = "node2_pub"];</code>
     */
    public function getNode2Pub()
    {
        return $this->node2_pub;
    }

    /**
     * <code>string node2_pub = 5[json_name = "node2_pub"];</code>
     */
    public function setNode2Pub($var)
    {
        GPBUtil::checkString($var, True);
        $this->node2_pub = $var;
    }

    /**
     * <code>int64 capacity = 6[json_name = "capacity"];</code>
     */
    public function getCapacity()
    {
        return $this->capacity;
    }

    /**
     * <code>int64 capacity = 6[json_name = "capacity"];</code>
     */
    public function setCapacity($var)
    {
        GPBUtil::checkInt64($var);
        $this->capacity = $var;
    }

    /**
     * <code>.lnrpc.RoutingPolicy node1_policy = 7[json_name = "node1_policy"];</code>
     */
    public function getNode1Policy()
    {
        return $this->node1_policy;
    }

    /**
     * <code>.lnrpc.RoutingPolicy node1_policy = 7[json_name = "node1_policy"];</code>
     */
    public function setNode1Policy(&$var)
    {
        GPBUtil::checkMessage($var, \Lnrpc\RoutingPolicy::class);
        $this->node1_policy = $var;
    }

    /**
     * <code>.lnrpc.RoutingPolicy node2_policy = 8[json_name = "node2_policy"];</code>
     */
    public function getNode2Policy()
    {
        return $this->node2_policy;
    }

    /**
     * <code>.lnrpc.RoutingPolicy node2_policy = 8[json_name = "node2_policy"];</code>
     */
    public function setNode2Policy(&$var)
    {
        GPBUtil::checkMessage($var, \Lnrpc\RoutingPolicy::class);
        $this->node2_policy = $var;
    }

}

