<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

namespace Lnrpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>lnrpc.ChannelGraph</code>
 */
class ChannelGraph extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>repeated .lnrpc.LightningNode nodes = 1[json_name = "nodes"];</code>
     */
    private $nodes;
    /**
     * <code>repeated .lnrpc.ChannelEdge edges = 2[json_name = "edges"];</code>
     */
    private $edges;

    public function __construct() {
        \GPBMetadata\Rpc::initOnce();
        parent::__construct();
    }

    /**
     * <code>repeated .lnrpc.LightningNode nodes = 1[json_name = "nodes"];</code>
     */
    public function getNodes()
    {
        return $this->nodes;
    }

    /**
     * <code>repeated .lnrpc.LightningNode nodes = 1[json_name = "nodes"];</code>
     */
    public function setNodes(&$var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Lnrpc\LightningNode::class);
        $this->nodes = $arr;
    }

    /**
     * <code>repeated .lnrpc.ChannelEdge edges = 2[json_name = "edges"];</code>
     */
    public function getEdges()
    {
        return $this->edges;
    }

    /**
     * <code>repeated .lnrpc.ChannelEdge edges = 2[json_name = "edges"];</code>
     */
    public function setEdges(&$var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Lnrpc\ChannelEdge::class);
        $this->edges = $arr;
    }

}

