<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

namespace Lnrpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>lnrpc.CloseStatusUpdate</code>
 */
class CloseStatusUpdate extends \Google\Protobuf\Internal\Message
{
    protected $update;

    public function __construct() {
        \GPBMetadata\Rpc::initOnce();
        parent::__construct();
    }

    /**
     * <code>.lnrpc.PendingUpdate close_pending = 1[json_name = "close_pending"];</code>
     */
    public function getClosePending()
    {
        return $this->readOneof(1);
    }

    /**
     * <code>.lnrpc.PendingUpdate close_pending = 1[json_name = "close_pending"];</code>
     */
    public function setClosePending(&$var)
    {
        GPBUtil::checkMessage($var, \Lnrpc\PendingUpdate::class);
        $this->writeOneof(1, $var);
    }

    /**
     * <code>.lnrpc.ConfirmationUpdate confirmation = 2[json_name = "confirmation"];</code>
     */
    public function getConfirmation()
    {
        return $this->readOneof(2);
    }

    /**
     * <code>.lnrpc.ConfirmationUpdate confirmation = 2[json_name = "confirmation"];</code>
     */
    public function setConfirmation(&$var)
    {
        GPBUtil::checkMessage($var, \Lnrpc\ConfirmationUpdate::class);
        $this->writeOneof(2, $var);
    }

    /**
     * <code>.lnrpc.ChannelCloseUpdate chan_close = 3[json_name = "chan_close"];</code>
     */
    public function getChanClose()
    {
        return $this->readOneof(3);
    }

    /**
     * <code>.lnrpc.ChannelCloseUpdate chan_close = 3[json_name = "chan_close"];</code>
     */
    public function setChanClose(&$var)
    {
        GPBUtil::checkMessage($var, \Lnrpc\ChannelCloseUpdate::class);
        $this->writeOneof(3, $var);
    }

    public function getUpdate()
    {
        return $this->whichOneof("update");
    }

}

