<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

namespace Lnrpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>lnrpc.CloseChannelRequest</code>
 */
class CloseChannelRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>.lnrpc.ChannelPoint channel_point = 1;</code>
     */
    private $channel_point = null;
    /**
     * <code>int64 time_limit = 2;</code>
     */
    private $time_limit = 0;
    /**
     * <code>bool force = 3;</code>
     */
    private $force = false;

    public function __construct() {
        \GPBMetadata\Rpc::initOnce();
        parent::__construct();
    }

    /**
     * <code>.lnrpc.ChannelPoint channel_point = 1;</code>
     */
    public function getChannelPoint()
    {
        return $this->channel_point;
    }

    /**
     * <code>.lnrpc.ChannelPoint channel_point = 1;</code>
     */
    public function setChannelPoint(&$var)
    {
        GPBUtil::checkMessage($var, \Lnrpc\ChannelPoint::class);
        $this->channel_point = $var;
    }

    /**
     * <code>int64 time_limit = 2;</code>
     */
    public function getTimeLimit()
    {
        return $this->time_limit;
    }

    /**
     * <code>int64 time_limit = 2;</code>
     */
    public function setTimeLimit($var)
    {
        GPBUtil::checkInt64($var);
        $this->time_limit = $var;
    }

    /**
     * <code>bool force = 3;</code>
     */
    public function getForce()
    {
        return $this->force;
    }

    /**
     * <code>bool force = 3;</code>
     */
    public function setForce($var)
    {
        GPBUtil::checkBool($var);
        $this->force = $var;
    }

}

