<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

namespace Lnrpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>lnrpc.ClosedChannelUpdate</code>
 */
class ClosedChannelUpdate extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>uint64 chan_id = 1;</code>
     */
    private $chan_id = 0;
    /**
     * <code>int64 capacity = 2;</code>
     */
    private $capacity = 0;
    /**
     * <code>uint32 closed_height = 3;</code>
     */
    private $closed_height = 0;
    /**
     * <code>.lnrpc.ChannelPoint chan_point = 4;</code>
     */
    private $chan_point = null;

    public function __construct() {
        \GPBMetadata\Rpc::initOnce();
        parent::__construct();
    }

    /**
     * <code>uint64 chan_id = 1;</code>
     */
    public function getChanId()
    {
        return $this->chan_id;
    }

    /**
     * <code>uint64 chan_id = 1;</code>
     */
    public function setChanId($var)
    {
        GPBUtil::checkUint64($var);
        $this->chan_id = $var;
    }

    /**
     * <code>int64 capacity = 2;</code>
     */
    public function getCapacity()
    {
        return $this->capacity;
    }

    /**
     * <code>int64 capacity = 2;</code>
     */
    public function setCapacity($var)
    {
        GPBUtil::checkInt64($var);
        $this->capacity = $var;
    }

    /**
     * <code>uint32 closed_height = 3;</code>
     */
    public function getClosedHeight()
    {
        return $this->closed_height;
    }

    /**
     * <code>uint32 closed_height = 3;</code>
     */
    public function setClosedHeight($var)
    {
        GPBUtil::checkUint32($var);
        $this->closed_height = $var;
    }

    /**
     * <code>.lnrpc.ChannelPoint chan_point = 4;</code>
     */
    public function getChanPoint()
    {
        return $this->chan_point;
    }

    /**
     * <code>.lnrpc.ChannelPoint chan_point = 4;</code>
     */
    public function setChanPoint(&$var)
    {
        GPBUtil::checkMessage($var, \Lnrpc\ChannelPoint::class);
        $this->chan_point = $var;
    }

}

