<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

namespace Lnrpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>lnrpc.ConnectPeerRequest</code>
 */
class ConnectPeerRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>.lnrpc.LightningAddress addr = 1;</code>
     */
    private $addr = null;
    /**
     * <code>bool perm = 2;</code>
     */
    private $perm = false;

    public function __construct() {
        \GPBMetadata\Rpc::initOnce();
        parent::__construct();
    }

    /**
     * <code>.lnrpc.LightningAddress addr = 1;</code>
     */
    public function getAddr()
    {
        return $this->addr;
    }

    /**
     * <code>.lnrpc.LightningAddress addr = 1;</code>
     */
    public function setAddr(&$var)
    {
        GPBUtil::checkMessage($var, \Lnrpc\LightningAddress::class);
        $this->addr = $var;
    }

    /**
     * <code>bool perm = 2;</code>
     */
    public function getPerm()
    {
        return $this->perm;
    }

    /**
     * <code>bool perm = 2;</code>
     */
    public function setPerm($var)
    {
        GPBUtil::checkBool($var);
        $this->perm = $var;
    }

}

