<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

namespace Lnrpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>lnrpc.DebugLevelRequest</code>
 */
class DebugLevelRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bool show = 1;</code>
     */
    private $show = false;
    /**
     * Generated from protobuf field <code>string level_spec = 2;</code>
     */
    private $level_spec = '';

    public function __construct() {
        \GPBMetadata\Rpc::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>bool show = 1;</code>
     * @return bool
     */
    public function getShow()
    {
        return $this->show;
    }

    /**
     * Generated from protobuf field <code>bool show = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setShow($var)
    {
        GPBUtil::checkBool($var);
        $this->show = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string level_spec = 2;</code>
     * @return string
     */
    public function getLevelSpec()
    {
        return $this->level_spec;
    }

    /**
     * Generated from protobuf field <code>string level_spec = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setLevelSpec($var)
    {
        GPBUtil::checkString($var, True);
        $this->level_spec = $var;

        return $this;
    }

}

