<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

namespace Lnrpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>lnrpc.DisconnectPeerRequest</code>
 */
class DisconnectPeerRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>string pub_key = 1[json_name = "pub_key"];</code>
     */
    private $pub_key = '';

    public function __construct() {
        \GPBMetadata\Rpc::initOnce();
        parent::__construct();
    }

    /**
     * <code>string pub_key = 1[json_name = "pub_key"];</code>
     */
    public function getPubKey()
    {
        return $this->pub_key;
    }

    /**
     * <code>string pub_key = 1[json_name = "pub_key"];</code>
     */
    public function setPubKey($var)
    {
        GPBUtil::checkString($var, True);
        $this->pub_key = $var;
    }

}

