<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

namespace Lnrpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>lnrpc.FeeLimit</code>
 */
class FeeLimit extends \Google\Protobuf\Internal\Message
{
    protected $limit;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $fixed
     *          &#47; The fee limit expressed as a fixed amount of satoshis.
     *     @type int|string $percent
     *          &#47; The fee limit expressed as a percentage of the payment amount.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Rpc::initOnce();
        parent::__construct($data);
    }

    /**
     *&#47; The fee limit expressed as a fixed amount of satoshis.
     *
     * Generated from protobuf field <code>int64 fixed = 1;</code>
     * @return int|string
     */
    public function getFixed()
    {
        return $this->readOneof(1);
    }

    /**
     *&#47; The fee limit expressed as a fixed amount of satoshis.
     *
     * Generated from protobuf field <code>int64 fixed = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setFixed($var)
    {
        GPBUtil::checkInt64($var);
        $this->writeOneof(1, $var);

        return $this;
    }

    /**
     *&#47; The fee limit expressed as a percentage of the payment amount.
     *
     * Generated from protobuf field <code>int64 percent = 2;</code>
     * @return int|string
     */
    public function getPercent()
    {
        return $this->readOneof(2);
    }

    /**
     *&#47; The fee limit expressed as a percentage of the payment amount.
     *
     * Generated from protobuf field <code>int64 percent = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setPercent($var)
    {
        GPBUtil::checkInt64($var);
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getLimit()
    {
        return $this->whichOneof("limit");
    }

}

