<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

namespace Lnrpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>lnrpc.GraphTopologyUpdate</code>
 */
class GraphTopologyUpdate extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>repeated .lnrpc.NodeUpdate node_updates = 1;</code>
     */
    private $node_updates;
    /**
     * <code>repeated .lnrpc.ChannelEdgeUpdate channel_updates = 2;</code>
     */
    private $channel_updates;
    /**
     * <code>repeated .lnrpc.ClosedChannelUpdate closed_chans = 3;</code>
     */
    private $closed_chans;

    public function __construct() {
        \GPBMetadata\Rpc::initOnce();
        parent::__construct();
    }

    /**
     * <code>repeated .lnrpc.NodeUpdate node_updates = 1;</code>
     */
    public function getNodeUpdates()
    {
        return $this->node_updates;
    }

    /**
     * <code>repeated .lnrpc.NodeUpdate node_updates = 1;</code>
     */
    public function setNodeUpdates(&$var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Lnrpc\NodeUpdate::class);
        $this->node_updates = $arr;
    }

    /**
     * <code>repeated .lnrpc.ChannelEdgeUpdate channel_updates = 2;</code>
     */
    public function getChannelUpdates()
    {
        return $this->channel_updates;
    }

    /**
     * <code>repeated .lnrpc.ChannelEdgeUpdate channel_updates = 2;</code>
     */
    public function setChannelUpdates(&$var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Lnrpc\ChannelEdgeUpdate::class);
        $this->channel_updates = $arr;
    }

    /**
     * <code>repeated .lnrpc.ClosedChannelUpdate closed_chans = 3;</code>
     */
    public function getClosedChans()
    {
        return $this->closed_chans;
    }

    /**
     * <code>repeated .lnrpc.ClosedChannelUpdate closed_chans = 3;</code>
     */
    public function setClosedChans(&$var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Lnrpc\ClosedChannelUpdate::class);
        $this->closed_chans = $arr;
    }

}

