<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

namespace Lnrpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>lnrpc.Hop</code>
 */
class Hop extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>uint64 chan_id = 1[json_name = "chan_id"];</code>
     */
    private $chan_id = 0;
    /**
     * <code>int64 chan_capacity = 2[json_name = "chan_capacity"];</code>
     */
    private $chan_capacity = 0;
    /**
     * <code>int64 amt_to_forward = 3[json_name = "amt_to_forward"];</code>
     */
    private $amt_to_forward = 0;
    /**
     * <code>int64 fee = 4[json_name = "fee"];</code>
     */
    private $fee = 0;

    public function __construct() {
        \GPBMetadata\Rpc::initOnce();
        parent::__construct();
    }

    /**
     * <code>uint64 chan_id = 1[json_name = "chan_id"];</code>
     */
    public function getChanId()
    {
        return $this->chan_id;
    }

    /**
     * <code>uint64 chan_id = 1[json_name = "chan_id"];</code>
     */
    public function setChanId($var)
    {
        GPBUtil::checkUint64($var);
        $this->chan_id = $var;
    }

    /**
     * <code>int64 chan_capacity = 2[json_name = "chan_capacity"];</code>
     */
    public function getChanCapacity()
    {
        return $this->chan_capacity;
    }

    /**
     * <code>int64 chan_capacity = 2[json_name = "chan_capacity"];</code>
     */
    public function setChanCapacity($var)
    {
        GPBUtil::checkInt64($var);
        $this->chan_capacity = $var;
    }

    /**
     * <code>int64 amt_to_forward = 3[json_name = "amt_to_forward"];</code>
     */
    public function getAmtToForward()
    {
        return $this->amt_to_forward;
    }

    /**
     * <code>int64 amt_to_forward = 3[json_name = "amt_to_forward"];</code>
     */
    public function setAmtToForward($var)
    {
        GPBUtil::checkInt64($var);
        $this->amt_to_forward = $var;
    }

    /**
     * <code>int64 fee = 4[json_name = "fee"];</code>
     */
    public function getFee()
    {
        return $this->fee;
    }

    /**
     * <code>int64 fee = 4[json_name = "fee"];</code>
     */
    public function setFee($var)
    {
        GPBUtil::checkInt64($var);
        $this->fee = $var;
    }

}

