<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

namespace Lnrpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>lnrpc.Invoice</code>
 */
class Invoice extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string memo = 1[json_name = "memo"];</code>
     */
    private $memo = '';
    /**
     * Generated from protobuf field <code>bytes receipt = 2[json_name = "receipt"];</code>
     */
    private $receipt = '';
    /**
     * Generated from protobuf field <code>bytes r_preimage = 3[json_name = "r_preimage"];</code>
     */
    private $r_preimage = '';
    /**
     * Generated from protobuf field <code>bytes r_hash = 4[json_name = "r_hash"];</code>
     */
    private $r_hash = '';
    /**
     * Generated from protobuf field <code>int64 value = 5[json_name = "value"];</code>
     */
    private $value = 0;
    /**
     * Generated from protobuf field <code>bool settled = 6[json_name = "settled"];</code>
     */
    private $settled = false;
    /**
     * Generated from protobuf field <code>int64 creation_date = 7[json_name = "creation_date"];</code>
     */
    private $creation_date = 0;
    /**
     * Generated from protobuf field <code>int64 settle_date = 8[json_name = "settle_date"];</code>
     */
    private $settle_date = 0;
    /**
     * Generated from protobuf field <code>string payment_request = 9[json_name = "payment_request"];</code>
     */
    private $payment_request = '';

    public function __construct() {
        \GPBMetadata\Rpc::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>string memo = 1[json_name = "memo"];</code>
     * @return string
     */
    public function getMemo()
    {
        return $this->memo;
    }

    /**
     * Generated from protobuf field <code>string memo = 1[json_name = "memo"];</code>
     * @param string $var
     * @return $this
     */
    public function setMemo($var)
    {
        GPBUtil::checkString($var, True);
        $this->memo = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes receipt = 2[json_name = "receipt"];</code>
     * @return string
     */
    public function getReceipt()
    {
        return $this->receipt;
    }

    /**
     * Generated from protobuf field <code>bytes receipt = 2[json_name = "receipt"];</code>
     * @param string $var
     * @return $this
     */
    public function setReceipt($var)
    {
        GPBUtil::checkString($var, False);
        $this->receipt = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes r_preimage = 3[json_name = "r_preimage"];</code>
     * @return string
     */
    public function getRPreimage()
    {
        return $this->r_preimage;
    }

    /**
     * Generated from protobuf field <code>bytes r_preimage = 3[json_name = "r_preimage"];</code>
     * @param string $var
     * @return $this
     */
    public function setRPreimage($var)
    {
        GPBUtil::checkString($var, False);
        $this->r_preimage = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes r_hash = 4[json_name = "r_hash"];</code>
     * @return string
     */
    public function getRHash()
    {
        return $this->r_hash;
    }

    /**
     * Generated from protobuf field <code>bytes r_hash = 4[json_name = "r_hash"];</code>
     * @param string $var
     * @return $this
     */
    public function setRHash($var)
    {
        GPBUtil::checkString($var, False);
        $this->r_hash = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 value = 5[json_name = "value"];</code>
     * @return int|string
     */
    public function getValue()
    {
        return $this->value;
    }

    /**
     * Generated from protobuf field <code>int64 value = 5[json_name = "value"];</code>
     * @param int|string $var
     * @return $this
     */
    public function setValue($var)
    {
        GPBUtil::checkInt64($var);
        $this->value = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool settled = 6[json_name = "settled"];</code>
     * @return bool
     */
    public function getSettled()
    {
        return $this->settled;
    }

    /**
     * Generated from protobuf field <code>bool settled = 6[json_name = "settled"];</code>
     * @param bool $var
     * @return $this
     */
    public function setSettled($var)
    {
        GPBUtil::checkBool($var);
        $this->settled = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 creation_date = 7[json_name = "creation_date"];</code>
     * @return int|string
     */
    public function getCreationDate()
    {
        return $this->creation_date;
    }

    /**
     * Generated from protobuf field <code>int64 creation_date = 7[json_name = "creation_date"];</code>
     * @param int|string $var
     * @return $this
     */
    public function setCreationDate($var)
    {
        GPBUtil::checkInt64($var);
        $this->creation_date = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 settle_date = 8[json_name = "settle_date"];</code>
     * @return int|string
     */
    public function getSettleDate()
    {
        return $this->settle_date;
    }

    /**
     * Generated from protobuf field <code>int64 settle_date = 8[json_name = "settle_date"];</code>
     * @param int|string $var
     * @return $this
     */
    public function setSettleDate($var)
    {
        GPBUtil::checkInt64($var);
        $this->settle_date = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string payment_request = 9[json_name = "payment_request"];</code>
     * @return string
     */
    public function getPaymentRequest()
    {
        return $this->payment_request;
    }

    /**
     * Generated from protobuf field <code>string payment_request = 9[json_name = "payment_request"];</code>
     * @param string $var
     * @return $this
     */
    public function setPaymentRequest($var)
    {
        GPBUtil::checkString($var, True);
        $this->payment_request = $var;

        return $this;
    }

}

