<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

namespace Lnrpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>lnrpc.LightningNode</code>
 */
class LightningNode extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 last_update = 1[json_name = "last_update"];</code>
     */
    private $last_update = 0;
    /**
     * Generated from protobuf field <code>string pub_key = 2[json_name = "pub_key"];</code>
     */
    private $pub_key = '';
    /**
     * Generated from protobuf field <code>string alias = 3[json_name = "alias"];</code>
     */
    private $alias = '';
    /**
     * Generated from protobuf field <code>repeated .lnrpc.NodeAddress addresses = 4[json_name = "addresses"];</code>
     */
    private $addresses;

    public function __construct() {
        \GPBMetadata\Rpc::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>uint32 last_update = 1[json_name = "last_update"];</code>
     * @return int
     */
    public function getLastUpdate()
    {
        return $this->last_update;
    }

    /**
     * Generated from protobuf field <code>uint32 last_update = 1[json_name = "last_update"];</code>
     * @param int $var
     * @return $this
     */
    public function setLastUpdate($var)
    {
        GPBUtil::checkUint32($var);
        $this->last_update = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string pub_key = 2[json_name = "pub_key"];</code>
     * @return string
     */
    public function getPubKey()
    {
        return $this->pub_key;
    }

    /**
     * Generated from protobuf field <code>string pub_key = 2[json_name = "pub_key"];</code>
     * @param string $var
     * @return $this
     */
    public function setPubKey($var)
    {
        GPBUtil::checkString($var, True);
        $this->pub_key = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string alias = 3[json_name = "alias"];</code>
     * @return string
     */
    public function getAlias()
    {
        return $this->alias;
    }

    /**
     * Generated from protobuf field <code>string alias = 3[json_name = "alias"];</code>
     * @param string $var
     * @return $this
     */
    public function setAlias($var)
    {
        GPBUtil::checkString($var, True);
        $this->alias = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .lnrpc.NodeAddress addresses = 4[json_name = "addresses"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getAddresses()
    {
        return $this->addresses;
    }

    /**
     * Generated from protobuf field <code>repeated .lnrpc.NodeAddress addresses = 4[json_name = "addresses"];</code>
     * @param \Lnrpc\NodeAddress[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setAddresses($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Lnrpc\NodeAddress::class);
        $this->addresses = $arr;

        return $this;
    }

}

