<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

namespace Lnrpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>lnrpc.ListPaymentsResponse</code>
 */
class ListPaymentsResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>repeated .lnrpc.Payment payments = 1[json_name = "payments"];</code>
     */
    private $payments;

    public function __construct() {
        \GPBMetadata\Rpc::initOnce();
        parent::__construct();
    }

    /**
     * <code>repeated .lnrpc.Payment payments = 1[json_name = "payments"];</code>
     */
    public function getPayments()
    {
        return $this->payments;
    }

    /**
     * <code>repeated .lnrpc.Payment payments = 1[json_name = "payments"];</code>
     */
    public function setPayments(&$var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Lnrpc\Payment::class);
        $this->payments = $arr;
    }

}

