<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

namespace Lnrpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>lnrpc.ListInvoiceRequest</code>
 */
class ListInvoiceRequest extends \Google\Protobuf\Internal\Message
{
    /**
     *&#47; If set, only unsettled invoices will be returned in the response.
     *
     * Generated from protobuf field <code>bool pending_only = 1[json_name = "pending_only"];</code>
     */
    private $pending_only = false;
    /**
     **
     *The index of an invoice that will be used as either the start or end of a
     *query to determine which invoices should be returned in the response.
     *
     * Generated from protobuf field <code>uint64 index_offset = 4[json_name = "index_offset"];</code>
     */
    private $index_offset = 0;
    /**
     *&#47; The max number of invoices to return in the response to this query.
     *
     * Generated from protobuf field <code>uint64 num_max_invoices = 5[json_name = "num_max_invoices"];</code>
     */
    private $num_max_invoices = 0;
    /**
     **
     *If set, the invoices returned will result from seeking backwards from the
     *specified index offset. This can be used to paginate backwards.
     *
     * Generated from protobuf field <code>bool reversed = 6[json_name = "reversed"];</code>
     */
    private $reversed = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $pending_only
     *          &#47; If set, only unsettled invoices will be returned in the response.
     *     @type int|string $index_offset
     *          *
     *          The index of an invoice that will be used as either the start or end of a
     *          query to determine which invoices should be returned in the response.
     *     @type int|string $num_max_invoices
     *          &#47; The max number of invoices to return in the response to this query.
     *     @type bool $reversed
     *          *
     *          If set, the invoices returned will result from seeking backwards from the
     *          specified index offset. This can be used to paginate backwards.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Rpc::initOnce();
        parent::__construct($data);
    }

    /**
     *&#47; If set, only unsettled invoices will be returned in the response.
     *
     * Generated from protobuf field <code>bool pending_only = 1[json_name = "pending_only"];</code>
     * @return bool
     */
    public function getPendingOnly()
    {
        return $this->pending_only;
    }

    /**
     *&#47; If set, only unsettled invoices will be returned in the response.
     *
     * Generated from protobuf field <code>bool pending_only = 1[json_name = "pending_only"];</code>
     * @param bool $var
     * @return $this
     */
    public function setPendingOnly($var)
    {
        GPBUtil::checkBool($var);
        $this->pending_only = $var;

        return $this;
    }

    /**
     **
     *The index of an invoice that will be used as either the start or end of a
     *query to determine which invoices should be returned in the response.
     *
     * Generated from protobuf field <code>uint64 index_offset = 4[json_name = "index_offset"];</code>
     * @return int|string
     */
    public function getIndexOffset()
    {
        return $this->index_offset;
    }

    /**
     **
     *The index of an invoice that will be used as either the start or end of a
     *query to determine which invoices should be returned in the response.
     *
     * Generated from protobuf field <code>uint64 index_offset = 4[json_name = "index_offset"];</code>
     * @param int|string $var
     * @return $this
     */
    public function setIndexOffset($var)
    {
        GPBUtil::checkUint64($var);
        $this->index_offset = $var;

        return $this;
    }

    /**
     *&#47; The max number of invoices to return in the response to this query.
     *
     * Generated from protobuf field <code>uint64 num_max_invoices = 5[json_name = "num_max_invoices"];</code>
     * @return int|string
     */
    public function getNumMaxInvoices()
    {
        return $this->num_max_invoices;
    }

    /**
     *&#47; The max number of invoices to return in the response to this query.
     *
     * Generated from protobuf field <code>uint64 num_max_invoices = 5[json_name = "num_max_invoices"];</code>
     * @param int|string $var
     * @return $this
     */
    public function setNumMaxInvoices($var)
    {
        GPBUtil::checkUint64($var);
        $this->num_max_invoices = $var;

        return $this;
    }

    /**
     **
     *If set, the invoices returned will result from seeking backwards from the
     *specified index offset. This can be used to paginate backwards.
     *
     * Generated from protobuf field <code>bool reversed = 6[json_name = "reversed"];</code>
     * @return bool
     */
    public function getReversed()
    {
        return $this->reversed;
    }

    /**
     **
     *If set, the invoices returned will result from seeking backwards from the
     *specified index offset. This can be used to paginate backwards.
     *
     * Generated from protobuf field <code>bool reversed = 6[json_name = "reversed"];</code>
     * @param bool $var
     * @return $this
     */
    public function setReversed($var)
    {
        GPBUtil::checkBool($var);
        $this->reversed = $var;

        return $this;
    }

}

