<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

namespace Lnrpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>lnrpc.NewAddressRequest</code>
 */
class NewAddressRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>.lnrpc.NewAddressRequest.AddressType type = 1;</code>
     */
    private $type = 0;

    public function __construct() {
        \GPBMetadata\Rpc::initOnce();
        parent::__construct();
    }

    /**
     * <code>.lnrpc.NewAddressRequest.AddressType type = 1;</code>
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * <code>.lnrpc.NewAddressRequest.AddressType type = 1;</code>
     */
    public function setType($var)
    {
        GPBUtil::checkEnum($var, \Lnrpc\NewAddressRequest_AddressType::class);
        $this->type = $var;
    }

}

