<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

namespace Lnrpc;

if (false) {
    /**
     * This class is deprecated. Use Lnrpc\NewAddressRequest\AddressType instead.
     * @deprecated
     */
    class NewAddressRequest_AddressType {}
}
class_exists(NewAddressRequest\AddressType::class);
@trigger_error('Lnrpc\NewAddressRequest_AddressType is deprecated and will be removed in the next major release. Use Lnrpc\NewAddressRequest\AddressType instead', E_USER_DEPRECATED);

