<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

namespace Lnrpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>lnrpc.NewAddressResponse</code>
 */
class NewAddressResponse extends \Google\Protobuf\Internal\Message
{
    /**
     *&#47; The newly generated wallet address
     *
     * Generated from protobuf field <code>string address = 1[json_name = "address"];</code>
     */
    private $address = '';

    public function __construct() {
        \GPBMetadata\Rpc::initOnce();
        parent::__construct();
    }

    /**
     *&#47; The newly generated wallet address
     *
     * Generated from protobuf field <code>string address = 1[json_name = "address"];</code>
     * @return string
     */
    public function getAddress()
    {
        return $this->address;
    }

    /**
     *&#47; The newly generated wallet address
     *
     * Generated from protobuf field <code>string address = 1[json_name = "address"];</code>
     * @param string $var
     * @return $this
     */
    public function setAddress($var)
    {
        GPBUtil::checkString($var, True);
        $this->address = $var;

        return $this;
    }

}

