<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

namespace Lnrpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>lnrpc.NodeUpdate</code>
 */
class NodeUpdate extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated string addresses = 1;</code>
     */
    private $addresses;
    /**
     * Generated from protobuf field <code>string identity_key = 2;</code>
     */
    private $identity_key = '';
    /**
     * Generated from protobuf field <code>bytes global_features = 3;</code>
     */
    private $global_features = '';
    /**
     * Generated from protobuf field <code>string alias = 4;</code>
     */
    private $alias = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $addresses
     *     @type string $identity_key
     *     @type string $global_features
     *     @type string $alias
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Rpc::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated string addresses = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getAddresses()
    {
        return $this->addresses;
    }

    /**
     * Generated from protobuf field <code>repeated string addresses = 1;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setAddresses($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->addresses = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string identity_key = 2;</code>
     * @return string
     */
    public function getIdentityKey()
    {
        return $this->identity_key;
    }

    /**
     * Generated from protobuf field <code>string identity_key = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setIdentityKey($var)
    {
        GPBUtil::checkString($var, True);
        $this->identity_key = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes global_features = 3;</code>
     * @return string
     */
    public function getGlobalFeatures()
    {
        return $this->global_features;
    }

    /**
     * Generated from protobuf field <code>bytes global_features = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setGlobalFeatures($var)
    {
        GPBUtil::checkString($var, False);
        $this->global_features = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string alias = 4;</code>
     * @return string
     */
    public function getAlias()
    {
        return $this->alias;
    }

    /**
     * Generated from protobuf field <code>string alias = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setAlias($var)
    {
        GPBUtil::checkString($var, True);
        $this->alias = $var;

        return $this;
    }

}

