<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

namespace Lnrpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>lnrpc.NodeAddress</code>
 */
class NodeAddress extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>string network = 1[json_name = "network"];</code>
     */
    private $network = '';
    /**
     * <code>string addr = 2[json_name = "addr"];</code>
     */
    private $addr = '';

    public function __construct() {
        \GPBMetadata\Rpc::initOnce();
        parent::__construct();
    }

    /**
     * <code>string network = 1[json_name = "network"];</code>
     */
    public function getNetwork()
    {
        return $this->network;
    }

    /**
     * <code>string network = 1[json_name = "network"];</code>
     */
    public function setNetwork($var)
    {
        GPBUtil::checkString($var, True);
        $this->network = $var;
    }

    /**
     * <code>string addr = 2[json_name = "addr"];</code>
     */
    public function getAddr()
    {
        return $this->addr;
    }

    /**
     * <code>string addr = 2[json_name = "addr"];</code>
     */
    public function setAddr($var)
    {
        GPBUtil::checkString($var, True);
        $this->addr = $var;
    }

}

