<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

namespace Lnrpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>lnrpc.OpenChannelRequest</code>
 */
class OpenChannelRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 target_peer_id = 1[json_name = "target_peer_id"];</code>
     */
    private $target_peer_id = 0;
    /**
     * Generated from protobuf field <code>bytes node_pubkey = 2[json_name = "node_pubkey"];</code>
     */
    private $node_pubkey = '';
    /**
     * Generated from protobuf field <code>string node_pubkey_string = 3[json_name = "node_pubkey_string"];</code>
     */
    private $node_pubkey_string = '';
    /**
     * Generated from protobuf field <code>int64 local_funding_amount = 4[json_name = "local_funding_amount"];</code>
     */
    private $local_funding_amount = 0;
    /**
     * Generated from protobuf field <code>int64 push_sat = 5[json_name = "push_sat"];</code>
     */
    private $push_sat = 0;
    /**
     * Generated from protobuf field <code>uint32 num_confs = 6[json_name = "num_confs"];</code>
     */
    private $num_confs = 0;

    public function __construct() {
        \GPBMetadata\Rpc::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>int32 target_peer_id = 1[json_name = "target_peer_id"];</code>
     * @return int
     */
    public function getTargetPeerId()
    {
        return $this->target_peer_id;
    }

    /**
     * Generated from protobuf field <code>int32 target_peer_id = 1[json_name = "target_peer_id"];</code>
     * @param int $var
     * @return $this
     */
    public function setTargetPeerId($var)
    {
        GPBUtil::checkInt32($var);
        $this->target_peer_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes node_pubkey = 2[json_name = "node_pubkey"];</code>
     * @return string
     */
    public function getNodePubkey()
    {
        return $this->node_pubkey;
    }

    /**
     * Generated from protobuf field <code>bytes node_pubkey = 2[json_name = "node_pubkey"];</code>
     * @param string $var
     * @return $this
     */
    public function setNodePubkey($var)
    {
        GPBUtil::checkString($var, False);
        $this->node_pubkey = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string node_pubkey_string = 3[json_name = "node_pubkey_string"];</code>
     * @return string
     */
    public function getNodePubkeyString()
    {
        return $this->node_pubkey_string;
    }

    /**
     * Generated from protobuf field <code>string node_pubkey_string = 3[json_name = "node_pubkey_string"];</code>
     * @param string $var
     * @return $this
     */
    public function setNodePubkeyString($var)
    {
        GPBUtil::checkString($var, True);
        $this->node_pubkey_string = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 local_funding_amount = 4[json_name = "local_funding_amount"];</code>
     * @return int|string
     */
    public function getLocalFundingAmount()
    {
        return $this->local_funding_amount;
    }

    /**
     * Generated from protobuf field <code>int64 local_funding_amount = 4[json_name = "local_funding_amount"];</code>
     * @param int|string $var
     * @return $this
     */
    public function setLocalFundingAmount($var)
    {
        GPBUtil::checkInt64($var);
        $this->local_funding_amount = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 push_sat = 5[json_name = "push_sat"];</code>
     * @return int|string
     */
    public function getPushSat()
    {
        return $this->push_sat;
    }

    /**
     * Generated from protobuf field <code>int64 push_sat = 5[json_name = "push_sat"];</code>
     * @param int|string $var
     * @return $this
     */
    public function setPushSat($var)
    {
        GPBUtil::checkInt64($var);
        $this->push_sat = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 num_confs = 6[json_name = "num_confs"];</code>
     * @return int
     */
    public function getNumConfs()
    {
        return $this->num_confs;
    }

    /**
     * Generated from protobuf field <code>uint32 num_confs = 6[json_name = "num_confs"];</code>
     * @param int $var
     * @return $this
     */
    public function setNumConfs($var)
    {
        GPBUtil::checkUint32($var);
        $this->num_confs = $var;

        return $this;
    }

}

