<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

namespace Lnrpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>lnrpc.OpenStatusUpdate</code>
 */
class OpenStatusUpdate extends \Google\Protobuf\Internal\Message
{
    protected $update;

    public function __construct() {
        \GPBMetadata\Rpc::initOnce();
        parent::__construct();
    }

    /**
     * <code>.lnrpc.PendingUpdate chan_pending = 1[json_name = "chan_pending"];</code>
     */
    public function getChanPending()
    {
        return $this->readOneof(1);
    }

    /**
     * <code>.lnrpc.PendingUpdate chan_pending = 1[json_name = "chan_pending"];</code>
     */
    public function setChanPending(&$var)
    {
        GPBUtil::checkMessage($var, \Lnrpc\PendingUpdate::class);
        $this->writeOneof(1, $var);
    }

    /**
     * <code>.lnrpc.ConfirmationUpdate confirmation = 2[json_name = "confirmation"];</code>
     */
    public function getConfirmation()
    {
        return $this->readOneof(2);
    }

    /**
     * <code>.lnrpc.ConfirmationUpdate confirmation = 2[json_name = "confirmation"];</code>
     */
    public function setConfirmation(&$var)
    {
        GPBUtil::checkMessage($var, \Lnrpc\ConfirmationUpdate::class);
        $this->writeOneof(2, $var);
    }

    /**
     * <code>.lnrpc.ChannelOpenUpdate chan_open = 3[json_name = "chan_open"];</code>
     */
    public function getChanOpen()
    {
        return $this->readOneof(3);
    }

    /**
     * <code>.lnrpc.ChannelOpenUpdate chan_open = 3[json_name = "chan_open"];</code>
     */
    public function setChanOpen(&$var)
    {
        GPBUtil::checkMessage($var, \Lnrpc\ChannelOpenUpdate::class);
        $this->writeOneof(3, $var);
    }

    public function getUpdate()
    {
        return $this->whichOneof("update");
    }

}

