<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

namespace Lnrpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>lnrpc.PayReq</code>
 */
class PayReq extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>string destination = 1[json_name = "destination"];</code>
     */
    private $destination = '';
    /**
     * <code>string payment_hash = 2[json_name = "payment_hash"];</code>
     */
    private $payment_hash = '';
    /**
     * <code>int64 num_satoshis = 3[json_name = "num_satoshis"];</code>
     */
    private $num_satoshis = 0;

    public function __construct() {
        \GPBMetadata\Rpc::initOnce();
        parent::__construct();
    }

    /**
     * <code>string destination = 1[json_name = "destination"];</code>
     */
    public function getDestination()
    {
        return $this->destination;
    }

    /**
     * <code>string destination = 1[json_name = "destination"];</code>
     */
    public function setDestination($var)
    {
        GPBUtil::checkString($var, True);
        $this->destination = $var;
    }

    /**
     * <code>string payment_hash = 2[json_name = "payment_hash"];</code>
     */
    public function getPaymentHash()
    {
        return $this->payment_hash;
    }

    /**
     * <code>string payment_hash = 2[json_name = "payment_hash"];</code>
     */
    public function setPaymentHash($var)
    {
        GPBUtil::checkString($var, True);
        $this->payment_hash = $var;
    }

    /**
     * <code>int64 num_satoshis = 3[json_name = "num_satoshis"];</code>
     */
    public function getNumSatoshis()
    {
        return $this->num_satoshis;
    }

    /**
     * <code>int64 num_satoshis = 3[json_name = "num_satoshis"];</code>
     */
    public function setNumSatoshis($var)
    {
        GPBUtil::checkInt64($var);
        $this->num_satoshis = $var;
    }

}

