<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

namespace Lnrpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>lnrpc.Peer</code>
 */
class Peer extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>string pub_key = 1[json_name = "pub_key"];</code>
     */
    private $pub_key = '';
    /**
     * <code>int32 peer_id = 2[json_name = "peer_id"];</code>
     */
    private $peer_id = 0;
    /**
     * <code>string address = 3[json_name = "address"];</code>
     */
    private $address = '';
    /**
     * <code>uint64 bytes_sent = 4[json_name = "bytes_sent"];</code>
     */
    private $bytes_sent = 0;
    /**
     * <code>uint64 bytes_recv = 5[json_name = "bytes_recv"];</code>
     */
    private $bytes_recv = 0;
    /**
     * <code>int64 sat_sent = 6[json_name = "sat_sent"];</code>
     */
    private $sat_sent = 0;
    /**
     * <code>int64 sat_recv = 7[json_name = "sat_recv"];</code>
     */
    private $sat_recv = 0;
    /**
     * <code>bool inbound = 8[json_name = "inbound"];</code>
     */
    private $inbound = false;
    /**
     * <code>int64 ping_time = 9[json_name = "ping_time"];</code>
     */
    private $ping_time = 0;

    public function __construct() {
        \GPBMetadata\Rpc::initOnce();
        parent::__construct();
    }

    /**
     * <code>string pub_key = 1[json_name = "pub_key"];</code>
     */
    public function getPubKey()
    {
        return $this->pub_key;
    }

    /**
     * <code>string pub_key = 1[json_name = "pub_key"];</code>
     */
    public function setPubKey($var)
    {
        GPBUtil::checkString($var, True);
        $this->pub_key = $var;
    }

    /**
     * <code>int32 peer_id = 2[json_name = "peer_id"];</code>
     */
    public function getPeerId()
    {
        return $this->peer_id;
    }

    /**
     * <code>int32 peer_id = 2[json_name = "peer_id"];</code>
     */
    public function setPeerId($var)
    {
        GPBUtil::checkInt32($var);
        $this->peer_id = $var;
    }

    /**
     * <code>string address = 3[json_name = "address"];</code>
     */
    public function getAddress()
    {
        return $this->address;
    }

    /**
     * <code>string address = 3[json_name = "address"];</code>
     */
    public function setAddress($var)
    {
        GPBUtil::checkString($var, True);
        $this->address = $var;
    }

    /**
     * <code>uint64 bytes_sent = 4[json_name = "bytes_sent"];</code>
     */
    public function getBytesSent()
    {
        return $this->bytes_sent;
    }

    /**
     * <code>uint64 bytes_sent = 4[json_name = "bytes_sent"];</code>
     */
    public function setBytesSent($var)
    {
        GPBUtil::checkUint64($var);
        $this->bytes_sent = $var;
    }

    /**
     * <code>uint64 bytes_recv = 5[json_name = "bytes_recv"];</code>
     */
    public function getBytesRecv()
    {
        return $this->bytes_recv;
    }

    /**
     * <code>uint64 bytes_recv = 5[json_name = "bytes_recv"];</code>
     */
    public function setBytesRecv($var)
    {
        GPBUtil::checkUint64($var);
        $this->bytes_recv = $var;
    }

    /**
     * <code>int64 sat_sent = 6[json_name = "sat_sent"];</code>
     */
    public function getSatSent()
    {
        return $this->sat_sent;
    }

    /**
     * <code>int64 sat_sent = 6[json_name = "sat_sent"];</code>
     */
    public function setSatSent($var)
    {
        GPBUtil::checkInt64($var);
        $this->sat_sent = $var;
    }

    /**
     * <code>int64 sat_recv = 7[json_name = "sat_recv"];</code>
     */
    public function getSatRecv()
    {
        return $this->sat_recv;
    }

    /**
     * <code>int64 sat_recv = 7[json_name = "sat_recv"];</code>
     */
    public function setSatRecv($var)
    {
        GPBUtil::checkInt64($var);
        $this->sat_recv = $var;
    }

    /**
     * <code>bool inbound = 8[json_name = "inbound"];</code>
     */
    public function getInbound()
    {
        return $this->inbound;
    }

    /**
     * <code>bool inbound = 8[json_name = "inbound"];</code>
     */
    public function setInbound($var)
    {
        GPBUtil::checkBool($var);
        $this->inbound = $var;
    }

    /**
     * <code>int64 ping_time = 9[json_name = "ping_time"];</code>
     */
    public function getPingTime()
    {
        return $this->ping_time;
    }

    /**
     * <code>int64 ping_time = 9[json_name = "ping_time"];</code>
     */
    public function setPingTime($var)
    {
        GPBUtil::checkInt64($var);
        $this->ping_time = $var;
    }

}

