<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

namespace Lnrpc;

if (false) {
    /**
     * This class is deprecated. Use Lnrpc\PendingChannelsResponse\PendingChannel instead.
     * @deprecated
     */
    class PendingChannelsResponse_PendingChannel {}
}
class_exists(PendingChannelsResponse\PendingChannel::class);
@trigger_error('Lnrpc\PendingChannelsResponse_PendingChannel is deprecated and will be removed in the next major release. Use Lnrpc\PendingChannelsResponse\PendingChannel instead', E_USER_DEPRECATED);

