<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

namespace Lnrpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>lnrpc.PendingChannelResponse.PendingOpenChannel</code>
 */
class PendingChannelResponse_PendingOpenChannel extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.lnrpc.PendingChannelResponse.PendingChannel channel = 1[json_name = "channel"];</code>
     */
    private $channel = null;
    /**
     * Generated from protobuf field <code>uint32 confirmation_height = 2[json_name = "confirmation_height"];</code>
     */
    private $confirmation_height = 0;
    /**
     * Generated from protobuf field <code>uint32 blocks_till_open = 3[json_name = "blocks_till_open"];</code>
     */
    private $blocks_till_open = 0;

    public function __construct() {
        \GPBMetadata\Rpc::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>.lnrpc.PendingChannelResponse.PendingChannel channel = 1[json_name = "channel"];</code>
     * @return \Lnrpc\PendingChannelResponse_PendingChannel
     */
    public function getChannel()
    {
        return $this->channel;
    }

    /**
     * Generated from protobuf field <code>.lnrpc.PendingChannelResponse.PendingChannel channel = 1[json_name = "channel"];</code>
     * @param \Lnrpc\PendingChannelResponse_PendingChannel $var
     * @return $this
     */
    public function setChannel($var)
    {
        GPBUtil::checkMessage($var, \Lnrpc\PendingChannelResponse_PendingChannel::class);
        $this->channel = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 confirmation_height = 2[json_name = "confirmation_height"];</code>
     * @return int
     */
    public function getConfirmationHeight()
    {
        return $this->confirmation_height;
    }

    /**
     * Generated from protobuf field <code>uint32 confirmation_height = 2[json_name = "confirmation_height"];</code>
     * @param int $var
     * @return $this
     */
    public function setConfirmationHeight($var)
    {
        GPBUtil::checkUint32($var);
        $this->confirmation_height = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 blocks_till_open = 3[json_name = "blocks_till_open"];</code>
     * @return int
     */
    public function getBlocksTillOpen()
    {
        return $this->blocks_till_open;
    }

    /**
     * Generated from protobuf field <code>uint32 blocks_till_open = 3[json_name = "blocks_till_open"];</code>
     * @param int $var
     * @return $this
     */
    public function setBlocksTillOpen($var)
    {
        GPBUtil::checkUint32($var);
        $this->blocks_till_open = $var;

        return $this;
    }

}

