<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

namespace Lnrpc;

if (false) {
    /**
     * This class is deprecated. Use Lnrpc\PendingChannelsResponse\WaitingCloseChannel instead.
     * @deprecated
     */
    class PendingChannelsResponse_WaitingCloseChannel {}
}
class_exists(PendingChannelsResponse\WaitingCloseChannel::class);
@trigger_error('Lnrpc\PendingChannelsResponse_WaitingCloseChannel is deprecated and will be removed in the next major release. Use Lnrpc\PendingChannelsResponse\WaitingCloseChannel instead', E_USER_DEPRECATED);

