<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

namespace Lnrpc;

if (false) {
    /**
     * This class is deprecated. Use Lnrpc\PendingChannelsResponse\PendingOpenChannel instead.
     * @deprecated
     */
    class PendingChannelsResponse_PendingOpenChannel {}
}
class_exists(PendingChannelsResponse\PendingOpenChannel::class);
@trigger_error('Lnrpc\PendingChannelsResponse_PendingOpenChannel is deprecated and will be removed in the next major release. Use Lnrpc\PendingChannelsResponse\PendingOpenChannel instead', E_USER_DEPRECATED);

