<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

namespace Lnrpc;

if (false) {
    /**
     * This class is deprecated. Use Lnrpc\PendingChannelsResponse\ForceClosedChannel instead.
     * @deprecated
     */
    class PendingChannelsResponse_ForceClosedChannel {}
}
class_exists(PendingChannelsResponse\ForceClosedChannel::class);
@trigger_error('Lnrpc\PendingChannelsResponse_ForceClosedChannel is deprecated and will be removed in the next major release. Use Lnrpc\PendingChannelsResponse\ForceClosedChannel instead', E_USER_DEPRECATED);

