<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

namespace Lnrpc;

if (false) {
    /**
     * This class is deprecated. Use Lnrpc\PendingChannelsResponse\ClosedChannel instead.
     * @deprecated
     */
    class PendingChannelsResponse_ClosedChannel {}
}
class_exists(PendingChannelsResponse\ClosedChannel::class);
@trigger_error('Lnrpc\PendingChannelsResponse_ClosedChannel is deprecated and will be removed in the next major release. Use Lnrpc\PendingChannelsResponse\ClosedChannel instead', E_USER_DEPRECATED);

