<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

namespace Lnrpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>lnrpc.QueryRoutesResponse</code>
 */
class QueryRoutesResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>repeated .lnrpc.Route routes = 1[json_name = "routes"];</code>
     */
    private $routes;

    public function __construct() {
        \GPBMetadata\Rpc::initOnce();
        parent::__construct();
    }

    /**
     * <code>repeated .lnrpc.Route routes = 1[json_name = "routes"];</code>
     */
    public function getRoutes()
    {
        return $this->routes;
    }

    /**
     * <code>repeated .lnrpc.Route routes = 1[json_name = "routes"];</code>
     */
    public function setRoutes(&$var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Lnrpc\Route::class);
        $this->routes = $arr;
    }

}

