<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

namespace Lnrpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>lnrpc.Route</code>
 */
class Route extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>uint32 total_time_lock = 1[json_name = "total_time_lock"];</code>
     */
    private $total_time_lock = 0;
    /**
     * <code>int64 total_fees = 2[json_name = "total_fees"];</code>
     */
    private $total_fees = 0;
    /**
     * <code>int64 total_amt = 3[json_name = "total_amt"];</code>
     */
    private $total_amt = 0;
    /**
     * <code>repeated .lnrpc.Hop hops = 4[json_name = "hops"];</code>
     */
    private $hops;

    public function __construct() {
        \GPBMetadata\Rpc::initOnce();
        parent::__construct();
    }

    /**
     * <code>uint32 total_time_lock = 1[json_name = "total_time_lock"];</code>
     */
    public function getTotalTimeLock()
    {
        return $this->total_time_lock;
    }

    /**
     * <code>uint32 total_time_lock = 1[json_name = "total_time_lock"];</code>
     */
    public function setTotalTimeLock($var)
    {
        GPBUtil::checkUint32($var);
        $this->total_time_lock = $var;
    }

    /**
     * <code>int64 total_fees = 2[json_name = "total_fees"];</code>
     */
    public function getTotalFees()
    {
        return $this->total_fees;
    }

    /**
     * <code>int64 total_fees = 2[json_name = "total_fees"];</code>
     */
    public function setTotalFees($var)
    {
        GPBUtil::checkInt64($var);
        $this->total_fees = $var;
    }

    /**
     * <code>int64 total_amt = 3[json_name = "total_amt"];</code>
     */
    public function getTotalAmt()
    {
        return $this->total_amt;
    }

    /**
     * <code>int64 total_amt = 3[json_name = "total_amt"];</code>
     */
    public function setTotalAmt($var)
    {
        GPBUtil::checkInt64($var);
        $this->total_amt = $var;
    }

    /**
     * <code>repeated .lnrpc.Hop hops = 4[json_name = "hops"];</code>
     */
    public function getHops()
    {
        return $this->hops;
    }

    /**
     * <code>repeated .lnrpc.Hop hops = 4[json_name = "hops"];</code>
     */
    public function setHops(&$var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Lnrpc\Hop::class);
        $this->hops = $arr;
    }

}

