<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

namespace Lnrpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>lnrpc.SendResponse</code>
 */
class SendResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>bytes payment_preimage = 1[json_name = "payment_preimage"];</code>
     */
    private $payment_preimage = '';
    /**
     * <code>.lnrpc.Route payment_route = 2[json_name = "payment_route"];</code>
     */
    private $payment_route = null;

    public function __construct() {
        \GPBMetadata\Rpc::initOnce();
        parent::__construct();
    }

    /**
     * <code>bytes payment_preimage = 1[json_name = "payment_preimage"];</code>
     */
    public function getPaymentPreimage()
    {
        return $this->payment_preimage;
    }

    /**
     * <code>bytes payment_preimage = 1[json_name = "payment_preimage"];</code>
     */
    public function setPaymentPreimage($var)
    {
        GPBUtil::checkString($var, False);
        $this->payment_preimage = $var;
    }

    /**
     * <code>.lnrpc.Route payment_route = 2[json_name = "payment_route"];</code>
     */
    public function getPaymentRoute()
    {
        return $this->payment_route;
    }

    /**
     * <code>.lnrpc.Route payment_route = 2[json_name = "payment_route"];</code>
     */
    public function setPaymentRoute(&$var)
    {
        GPBUtil::checkMessage($var, \Lnrpc\Route::class);
        $this->payment_route = $var;
    }

}

