<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

namespace Lnrpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>lnrpc.SendToRouteRequest</code>
 */
class SendToRouteRequest extends \Google\Protobuf\Internal\Message
{
    /**
     *&#47; The payment hash to use for the HTLC.
     *
     * Generated from protobuf field <code>bytes payment_hash = 1;</code>
     */
    private $payment_hash = '';
    /**
     *&#47; An optional hex-encoded payment hash to be used for the HTLC.
     *
     * Generated from protobuf field <code>string payment_hash_string = 2;</code>
     */
    private $payment_hash_string = '';
    /**
     *&#47; The set of routes that should be used to attempt to complete the payment.
     *
     * Generated from protobuf field <code>repeated .lnrpc.Route routes = 3;</code>
     */
    private $routes;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $payment_hash
     *          &#47; The payment hash to use for the HTLC.
     *     @type string $payment_hash_string
     *          &#47; An optional hex-encoded payment hash to be used for the HTLC.
     *     @type \Lnrpc\Route[]|\Google\Protobuf\Internal\RepeatedField $routes
     *          &#47; The set of routes that should be used to attempt to complete the payment.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Rpc::initOnce();
        parent::__construct($data);
    }

    /**
     *&#47; The payment hash to use for the HTLC.
     *
     * Generated from protobuf field <code>bytes payment_hash = 1;</code>
     * @return string
     */
    public function getPaymentHash()
    {
        return $this->payment_hash;
    }

    /**
     *&#47; The payment hash to use for the HTLC.
     *
     * Generated from protobuf field <code>bytes payment_hash = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setPaymentHash($var)
    {
        GPBUtil::checkString($var, False);
        $this->payment_hash = $var;

        return $this;
    }

    /**
     *&#47; An optional hex-encoded payment hash to be used for the HTLC.
     *
     * Generated from protobuf field <code>string payment_hash_string = 2;</code>
     * @return string
     */
    public function getPaymentHashString()
    {
        return $this->payment_hash_string;
    }

    /**
     *&#47; An optional hex-encoded payment hash to be used for the HTLC.
     *
     * Generated from protobuf field <code>string payment_hash_string = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setPaymentHashString($var)
    {
        GPBUtil::checkString($var, True);
        $this->payment_hash_string = $var;

        return $this;
    }

    /**
     *&#47; The set of routes that should be used to attempt to complete the payment.
     *
     * Generated from protobuf field <code>repeated .lnrpc.Route routes = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getRoutes()
    {
        return $this->routes;
    }

    /**
     *&#47; The set of routes that should be used to attempt to complete the payment.
     *
     * Generated from protobuf field <code>repeated .lnrpc.Route routes = 3;</code>
     * @param \Lnrpc\Route[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setRoutes($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Lnrpc\Route::class);
        $this->routes = $arr;

        return $this;
    }

}

