<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

namespace Lnrpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>lnrpc.SendRequest</code>
 */
class SendRequest extends \Google\Protobuf\Internal\Message
{
    /**
     *&#47; The identity pubkey of the payment recipient
     *
     * Generated from protobuf field <code>bytes dest = 1;</code>
     */
    private $dest = '';
    /**
     *&#47; The hex-encoded identity pubkey of the payment recipient
     *
     * Generated from protobuf field <code>string dest_string = 2;</code>
     */
    private $dest_string = '';
    /**
     *&#47; Number of satoshis to send.
     *
     * Generated from protobuf field <code>int64 amt = 3;</code>
     */
    private $amt = 0;
    /**
     *&#47; The hash to use within the payment's HTLC
     *
     * Generated from protobuf field <code>bytes payment_hash = 4;</code>
     */
    private $payment_hash = '';
    /**
     *&#47; The hex-encoded hash to use within the payment's HTLC
     *
     * Generated from protobuf field <code>string payment_hash_string = 5;</code>
     */
    private $payment_hash_string = '';
    /**
     **
     *A bare-bones invoice for a payment within the Lightning Network.  With the
     *details of the invoice, the sender has all the data necessary to send a
     *payment to the recipient.
     *
     * Generated from protobuf field <code>string payment_request = 6;</code>
     */
    private $payment_request = '';
    /**
     **
     *The CLTV delta from the current height that should be used to set the
     *timelock for the final hop.
     *
     * Generated from protobuf field <code>int32 final_cltv_delta = 7;</code>
     */
    private $final_cltv_delta = 0;
    /**
     **
     *The maximum number of satoshis that will be paid as a fee of the payment.
     *This value can be represented either as a percentage of the amount being
     *sent, or as a fixed amount of the maximum fee the user is willing the pay to
     *send the payment.
     *
     * Generated from protobuf field <code>.lnrpc.FeeLimit fee_limit = 8;</code>
     */
    private $fee_limit = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $dest
     *          &#47; The identity pubkey of the payment recipient
     *     @type string $dest_string
     *          &#47; The hex-encoded identity pubkey of the payment recipient
     *     @type int|string $amt
     *          &#47; Number of satoshis to send.
     *     @type string $payment_hash
     *          &#47; The hash to use within the payment's HTLC
     *     @type string $payment_hash_string
     *          &#47; The hex-encoded hash to use within the payment's HTLC
     *     @type string $payment_request
     *          *
     *          A bare-bones invoice for a payment within the Lightning Network.  With the
     *          details of the invoice, the sender has all the data necessary to send a
     *          payment to the recipient.
     *     @type int $final_cltv_delta
     *          *
     *          The CLTV delta from the current height that should be used to set the
     *          timelock for the final hop.
     *     @type \Lnrpc\FeeLimit $fee_limit
     *          *
     *          The maximum number of satoshis that will be paid as a fee of the payment.
     *          This value can be represented either as a percentage of the amount being
     *          sent, or as a fixed amount of the maximum fee the user is willing the pay to
     *          send the payment.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Rpc::initOnce();
        parent::__construct($data);
    }

    /**
     *&#47; The identity pubkey of the payment recipient
     *
     * Generated from protobuf field <code>bytes dest = 1;</code>
     * @return string
     */
    public function getDest()
    {
        return $this->dest;
    }

    /**
     *&#47; The identity pubkey of the payment recipient
     *
     * Generated from protobuf field <code>bytes dest = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setDest($var)
    {
        GPBUtil::checkString($var, False);
        $this->dest = $var;

        return $this;
    }

    /**
     *&#47; The hex-encoded identity pubkey of the payment recipient
     *
     * Generated from protobuf field <code>string dest_string = 2;</code>
     * @return string
     */
    public function getDestString()
    {
        return $this->dest_string;
    }

    /**
     *&#47; The hex-encoded identity pubkey of the payment recipient
     *
     * Generated from protobuf field <code>string dest_string = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setDestString($var)
    {
        GPBUtil::checkString($var, True);
        $this->dest_string = $var;

        return $this;
    }

    /**
     *&#47; Number of satoshis to send.
     *
     * Generated from protobuf field <code>int64 amt = 3;</code>
     * @return int|string
     */
    public function getAmt()
    {
        return $this->amt;
    }

    /**
     *&#47; Number of satoshis to send.
     *
     * Generated from protobuf field <code>int64 amt = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setAmt($var)
    {
        GPBUtil::checkInt64($var);
        $this->amt = $var;

        return $this;
    }

    /**
     *&#47; The hash to use within the payment's HTLC
     *
     * Generated from protobuf field <code>bytes payment_hash = 4;</code>
     * @return string
     */
    public function getPaymentHash()
    {
        return $this->payment_hash;
    }

    /**
     *&#47; The hash to use within the payment's HTLC
     *
     * Generated from protobuf field <code>bytes payment_hash = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setPaymentHash($var)
    {
        GPBUtil::checkString($var, False);
        $this->payment_hash = $var;

        return $this;
    }

    /**
     *&#47; The hex-encoded hash to use within the payment's HTLC
     *
     * Generated from protobuf field <code>string payment_hash_string = 5;</code>
     * @return string
     */
    public function getPaymentHashString()
    {
        return $this->payment_hash_string;
    }

    /**
     *&#47; The hex-encoded hash to use within the payment's HTLC
     *
     * Generated from protobuf field <code>string payment_hash_string = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setPaymentHashString($var)
    {
        GPBUtil::checkString($var, True);
        $this->payment_hash_string = $var;

        return $this;
    }

    /**
     **
     *A bare-bones invoice for a payment within the Lightning Network.  With the
     *details of the invoice, the sender has all the data necessary to send a
     *payment to the recipient.
     *
     * Generated from protobuf field <code>string payment_request = 6;</code>
     * @return string
     */
    public function getPaymentRequest()
    {
        return $this->payment_request;
    }

    /**
     **
     *A bare-bones invoice for a payment within the Lightning Network.  With the
     *details of the invoice, the sender has all the data necessary to send a
     *payment to the recipient.
     *
     * Generated from protobuf field <code>string payment_request = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setPaymentRequest($var)
    {
        GPBUtil::checkString($var, True);
        $this->payment_request = $var;

        return $this;
    }

    /**
     **
     *The CLTV delta from the current height that should be used to set the
     *timelock for the final hop.
     *
     * Generated from protobuf field <code>int32 final_cltv_delta = 7;</code>
     * @return int
     */
    public function getFinalCltvDelta()
    {
        return $this->final_cltv_delta;
    }

    /**
     **
     *The CLTV delta from the current height that should be used to set the
     *timelock for the final hop.
     *
     * Generated from protobuf field <code>int32 final_cltv_delta = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setFinalCltvDelta($var)
    {
        GPBUtil::checkInt32($var);
        $this->final_cltv_delta = $var;

        return $this;
    }

    /**
     **
     *The maximum number of satoshis that will be paid as a fee of the payment.
     *This value can be represented either as a percentage of the amount being
     *sent, or as a fixed amount of the maximum fee the user is willing the pay to
     *send the payment.
     *
     * Generated from protobuf field <code>.lnrpc.FeeLimit fee_limit = 8;</code>
     * @return \Lnrpc\FeeLimit
     */
    public function getFeeLimit()
    {
        return $this->fee_limit;
    }

    /**
     **
     *The maximum number of satoshis that will be paid as a fee of the payment.
     *This value can be represented either as a percentage of the amount being
     *sent, or as a fixed amount of the maximum fee the user is willing the pay to
     *send the payment.
     *
     * Generated from protobuf field <code>.lnrpc.FeeLimit fee_limit = 8;</code>
     * @param \Lnrpc\FeeLimit $var
     * @return $this
     */
    public function setFeeLimit($var)
    {
        GPBUtil::checkMessage($var, \Lnrpc\FeeLimit::class);
        $this->fee_limit = $var;

        return $this;
    }

}

