<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

namespace Lnrpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>lnrpc.SetAliasRequest</code>
 */
class SetAliasRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>string new_alias = 1;</code>
     */
    private $new_alias = '';

    public function __construct() {
        \GPBMetadata\Rpc::initOnce();
        parent::__construct();
    }

    /**
     * <code>string new_alias = 1;</code>
     */
    public function getNewAlias()
    {
        return $this->new_alias;
    }

    /**
     * <code>string new_alias = 1;</code>
     */
    public function setNewAlias($var)
    {
        GPBUtil::checkString($var, True);
        $this->new_alias = $var;
    }

}

