<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

namespace Lnrpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>lnrpc.Transaction</code>
 */
class Transaction extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>string tx_hash = 1[json_name = "tx_hash"];</code>
     */
    private $tx_hash = '';
    /**
     * <code>int64 amount = 2[json_name = "amount"];</code>
     */
    private $amount = 0;
    /**
     * <code>int32 num_confirmations = 3[json_name = "num_confirmations"];</code>
     */
    private $num_confirmations = 0;
    /**
     * <code>string block_hash = 4[json_name = "block_hash"];</code>
     */
    private $block_hash = '';
    /**
     * <code>int32 block_height = 5[json_name = "block_height"];</code>
     */
    private $block_height = 0;
    /**
     * <code>int64 time_stamp = 6[json_name = "time_stamp"];</code>
     */
    private $time_stamp = 0;
    /**
     * <code>int64 total_fees = 7[json_name = "total_fees"];</code>
     */
    private $total_fees = 0;

    public function __construct() {
        \GPBMetadata\Rpc::initOnce();
        parent::__construct();
    }

    /**
     * <code>string tx_hash = 1[json_name = "tx_hash"];</code>
     */
    public function getTxHash()
    {
        return $this->tx_hash;
    }

    /**
     * <code>string tx_hash = 1[json_name = "tx_hash"];</code>
     */
    public function setTxHash($var)
    {
        GPBUtil::checkString($var, True);
        $this->tx_hash = $var;
    }

    /**
     * <code>int64 amount = 2[json_name = "amount"];</code>
     */
    public function getAmount()
    {
        return $this->amount;
    }

    /**
     * <code>int64 amount = 2[json_name = "amount"];</code>
     */
    public function setAmount($var)
    {
        GPBUtil::checkInt64($var);
        $this->amount = $var;
    }

    /**
     * <code>int32 num_confirmations = 3[json_name = "num_confirmations"];</code>
     */
    public function getNumConfirmations()
    {
        return $this->num_confirmations;
    }

    /**
     * <code>int32 num_confirmations = 3[json_name = "num_confirmations"];</code>
     */
    public function setNumConfirmations($var)
    {
        GPBUtil::checkInt32($var);
        $this->num_confirmations = $var;
    }

    /**
     * <code>string block_hash = 4[json_name = "block_hash"];</code>
     */
    public function getBlockHash()
    {
        return $this->block_hash;
    }

    /**
     * <code>string block_hash = 4[json_name = "block_hash"];</code>
     */
    public function setBlockHash($var)
    {
        GPBUtil::checkString($var, True);
        $this->block_hash = $var;
    }

    /**
     * <code>int32 block_height = 5[json_name = "block_height"];</code>
     */
    public function getBlockHeight()
    {
        return $this->block_height;
    }

    /**
     * <code>int32 block_height = 5[json_name = "block_height"];</code>
     */
    public function setBlockHeight($var)
    {
        GPBUtil::checkInt32($var);
        $this->block_height = $var;
    }

    /**
     * <code>int64 time_stamp = 6[json_name = "time_stamp"];</code>
     */
    public function getTimeStamp()
    {
        return $this->time_stamp;
    }

    /**
     * <code>int64 time_stamp = 6[json_name = "time_stamp"];</code>
     */
    public function setTimeStamp($var)
    {
        GPBUtil::checkInt64($var);
        $this->time_stamp = $var;
    }

    /**
     * <code>int64 total_fees = 7[json_name = "total_fees"];</code>
     */
    public function getTotalFees()
    {
        return $this->total_fees;
    }

    /**
     * <code>int64 total_fees = 7[json_name = "total_fees"];</code>
     */
    public function setTotalFees($var)
    {
        GPBUtil::checkInt64($var);
        $this->total_fees = $var;
    }

}

