<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

namespace Lnrpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>lnrpc.TransactionDetails</code>
 */
class TransactionDetails extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>repeated .lnrpc.Transaction transactions = 1[json_name = "transactions"];</code>
     */
    private $transactions;

    public function __construct() {
        \GPBMetadata\Rpc::initOnce();
        parent::__construct();
    }

    /**
     * <code>repeated .lnrpc.Transaction transactions = 1[json_name = "transactions"];</code>
     */
    public function getTransactions()
    {
        return $this->transactions;
    }

    /**
     * <code>repeated .lnrpc.Transaction transactions = 1[json_name = "transactions"];</code>
     */
    public function setTransactions(&$var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Lnrpc\Transaction::class);
        $this->transactions = $arr;
    }

}

