<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

namespace Lnrpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>lnrpc.TransactionDetails</code>
 */
class TransactionDetails extends \Google\Protobuf\Internal\Message
{
    /**
     *&#47; The list of transactions relevant to the wallet.
     *
     * Generated from protobuf field <code>repeated .lnrpc.Transaction transactions = 1[json_name = "transactions"];</code>
     */
    private $transactions;

    public function __construct() {
        \GPBMetadata\Rpc::initOnce();
        parent::__construct();
    }

    /**
     *&#47; The list of transactions relevant to the wallet.
     *
     * Generated from protobuf field <code>repeated .lnrpc.Transaction transactions = 1[json_name = "transactions"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getTransactions()
    {
        return $this->transactions;
    }

    /**
     *&#47; The list of transactions relevant to the wallet.
     *
     * Generated from protobuf field <code>repeated .lnrpc.Transaction transactions = 1[json_name = "transactions"];</code>
     * @param \Lnrpc\Transaction[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setTransactions($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Lnrpc\Transaction::class);
        $this->transactions = $arr;

        return $this;
    }

}

