<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

namespace Lnrpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>lnrpc.VerifyMessageResponse</code>
 */
class VerifyMessageResponse extends \Google\Protobuf\Internal\Message
{
    /**
     *&#47; Whether the signature was valid over the given message
     *
     * Generated from protobuf field <code>bool valid = 1[json_name = "valid"];</code>
     */
    private $valid = false;
    /**
     *&#47; The pubkey recovered from the signature
     *
     * Generated from protobuf field <code>string pubkey = 2[json_name = "pubkey"];</code>
     */
    private $pubkey = '';

    public function __construct() {
        \GPBMetadata\Rpc::initOnce();
        parent::__construct();
    }

    /**
     *&#47; Whether the signature was valid over the given message
     *
     * Generated from protobuf field <code>bool valid = 1[json_name = "valid"];</code>
     * @return bool
     */
    public function getValid()
    {
        return $this->valid;
    }

    /**
     *&#47; Whether the signature was valid over the given message
     *
     * Generated from protobuf field <code>bool valid = 1[json_name = "valid"];</code>
     * @param bool $var
     * @return $this
     */
    public function setValid($var)
    {
        GPBUtil::checkBool($var);
        $this->valid = $var;

        return $this;
    }

    /**
     *&#47; The pubkey recovered from the signature
     *
     * Generated from protobuf field <code>string pubkey = 2[json_name = "pubkey"];</code>
     * @return string
     */
    public function getPubkey()
    {
        return $this->pubkey;
    }

    /**
     *&#47; The pubkey recovered from the signature
     *
     * Generated from protobuf field <code>string pubkey = 2[json_name = "pubkey"];</code>
     * @param string $var
     * @return $this
     */
    public function setPubkey($var)
    {
        GPBUtil::checkString($var, True);
        $this->pubkey = $var;

        return $this;
    }

}

