<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

namespace Lnrpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>lnrpc.VerifyMessageRequest</code>
 */
class VerifyMessageRequest extends \Google\Protobuf\Internal\Message
{
    /**
     *&#47; The message over which the signature is to be verified
     *
     * Generated from protobuf field <code>bytes msg = 1[json_name = "msg"];</code>
     */
    private $msg = '';
    /**
     *&#47; The signature to be verified over the given message
     *
     * Generated from protobuf field <code>string signature = 2[json_name = "signature"];</code>
     */
    private $signature = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $msg
     *          &#47; The message over which the signature is to be verified
     *     @type string $signature
     *          &#47; The signature to be verified over the given message
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Rpc::initOnce();
        parent::__construct($data);
    }

    /**
     *&#47; The message over which the signature is to be verified
     *
     * Generated from protobuf field <code>bytes msg = 1[json_name = "msg"];</code>
     * @return string
     */
    public function getMsg()
    {
        return $this->msg;
    }

    /**
     *&#47; The message over which the signature is to be verified
     *
     * Generated from protobuf field <code>bytes msg = 1[json_name = "msg"];</code>
     * @param string $var
     * @return $this
     */
    public function setMsg($var)
    {
        GPBUtil::checkString($var, False);
        $this->msg = $var;

        return $this;
    }

    /**
     *&#47; The signature to be verified over the given message
     *
     * Generated from protobuf field <code>string signature = 2[json_name = "signature"];</code>
     * @return string
     */
    public function getSignature()
    {
        return $this->signature;
    }

    /**
     *&#47; The signature to be verified over the given message
     *
     * Generated from protobuf field <code>string signature = 2[json_name = "signature"];</code>
     * @param string $var
     * @return $this
     */
    public function setSignature($var)
    {
        GPBUtil::checkString($var, True);
        $this->signature = $var;

        return $this;
    }

}

