<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

namespace Lnrpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>lnrpc.WalletBalanceRequest</code>
 */
class WalletBalanceRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>bool witness_only = 1;</code>
     */
    private $witness_only = false;

    public function __construct() {
        \GPBMetadata\Rpc::initOnce();
        parent::__construct();
    }

    /**
     * <code>bool witness_only = 1;</code>
     */
    public function getWitnessOnly()
    {
        return $this->witness_only;
    }

    /**
     * <code>bool witness_only = 1;</code>
     */
    public function setWitnessOnly($var)
    {
        GPBUtil::checkBool($var);
        $this->witness_only = $var;
    }

}

