<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

namespace Lnrpc\ChannelCloseSummary;

/**
 * Protobuf type <code>lnrpc.ChannelCloseSummary.ClosureType</code>
 */
class ClosureType
{
    /**
     * Generated from protobuf enum <code>COOPERATIVE_CLOSE = 0;</code>
     */
    const COOPERATIVE_CLOSE = 0;
    /**
     * Generated from protobuf enum <code>LOCAL_FORCE_CLOSE = 1;</code>
     */
    const LOCAL_FORCE_CLOSE = 1;
    /**
     * Generated from protobuf enum <code>REMOTE_FORCE_CLOSE = 2;</code>
     */
    const REMOTE_FORCE_CLOSE = 2;
    /**
     * Generated from protobuf enum <code>BREACH_CLOSE = 3;</code>
     */
    const BREACH_CLOSE = 3;
    /**
     * Generated from protobuf enum <code>FUNDING_CANCELED = 4;</code>
     */
    const FUNDING_CANCELED = 4;
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(ClosureType::class, \Lnrpc\ChannelCloseSummary_ClosureType::class);

